
import React from 'react';
import { GeneratedImage, AppRoute } from '../types';
import { Scissors, Shirt, Clock, Download, Trash2, Share2 } from 'lucide-react';
import toast from 'react-hot-toast';

interface MyLooksProps {
  looks: GeneratedImage[];
  onNavigate: (route: AppRoute) => void;
  onDelete: (id: string) => void;
}

export const MyLooks: React.FC<MyLooksProps> = ({ looks, onNavigate, onDelete }) => {

  const handleDownload = async (e: React.MouseEvent, look: GeneratedImage) => {
    e.stopPropagation();
    toast.success("Preparing download...");
    
    try {
        // If it's a remote URL, we need to fetch it as a blob to force download
        if (look.url.startsWith('http')) {
            const response = await fetch(look.url);
            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = `roopai-${look.type}-${look.id}.jpg`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            window.URL.revokeObjectURL(url);
        } else {
            // If it's a data URL, straightforward download
            const link = document.createElement('a');
            link.href = look.url;
            link.download = `roopai-${look.type}-${look.id}.jpg`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        }
    } catch (err) {
        console.error("Download failed", err);
        toast.error("Could not download image");
    }
  };

  const handleDelete = (e: React.MouseEvent, id: string) => {
      e.stopPropagation();
      if(confirm("Are you sure you want to delete this look?")) {
          onDelete(id);
          toast.success("Deleted");
      }
  }

  const handleShare = async (e: React.MouseEvent, look: GeneratedImage) => {
    e.stopPropagation();
    try {
        // Fetch blob if it's a remote URL
        const res = await fetch(look.url);
        const blob = await res.blob();
        const file = new File([blob], "roopai_look.jpg", { type: "image/jpeg" });
        
        if (navigator.share) {
            await navigator.share({
                title: 'My RoopAI Look',
                text: `Check out this ${look.type} style generated by RoopAI!`,
                files: [file]
            });
        } else {
            toast.error("Sharing not supported on this browser");
        }
    } catch(err) {
        console.error(err);
        // Fallback to simple link share
        if (navigator.share) {
             await navigator.share({
                title: 'My RoopAI Look',
                url: look.url
            });
        } else {
             await navigator.clipboard.writeText(look.url);
             toast.success("Link copied to clipboard");
        }
    }
  };
  
  if (looks.length === 0) {
      return (
        <div className="flex flex-col items-center justify-center h-[60vh] text-center space-y-6 animate-fade-in px-6">
            <div className="bg-gray-100 dark:bg-gray-800 p-8 rounded-full shadow-inner transition-colors">
               <Scissors className="w-12 h-12 text-gray-300 dark:text-gray-600" />
            </div>
            <div>
                <h3 className="font-heading font-bold text-xl text-neutral dark:text-white mb-2">No saved looks yet</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm leading-relaxed">
                    Your personal gallery is empty. <br/> Start styling to save your transformations!
                </p>
            </div>
            <button 
                onClick={() => onNavigate(AppRoute.TRY_HAIR)}
                className="bg-primary text-white px-6 py-3 rounded-xl font-semibold shadow-lg shadow-primary/30 hover:bg-primary/90 transition-all w-full max-w-xs"
            >
                Create Your First Look
            </button>
        </div>
      );
  }

  return (
    <div className="space-y-6 pb-24 animate-fade-in">
        <div className="flex items-center justify-between sticky top-0 z-10 bg-gray-50 py-4 dark:bg-gray-900 backdrop-blur-md bg-gray-50/90 dark:bg-gray-900/90 border-b border-gray-100 dark:border-gray-800 -mx-4 px-4 transition-colors duration-200">
            <div>
                <h2 className="text-2xl font-heading font-bold text-neutral dark:text-white">My Saved Looks</h2>
                <p className="text-sm text-gray-500 dark:text-gray-400">Your style evolution history</p>
            </div>
            <span className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 px-3 py-1 rounded-full text-xs font-bold text-neutral dark:text-gray-200 shadow-sm transition-colors">
                {looks.length} Saved
            </span>
        </div>

        <div className="grid grid-cols-2 gap-4">
            {looks.map((look) => (
                <div key={look.id} className="bg-white dark:bg-gray-800 rounded-2xl overflow-hidden shadow-sm border border-gray-100 dark:border-gray-700 group flex flex-col relative transition-colors">
                    <div className="aspect-[3/4] relative overflow-hidden bg-gray-100 dark:bg-gray-900">
                        <img 
                            src={look.url} 
                            alt={look.prompt} 
                            className="w-full h-full object-cover" 
                            loading="lazy"
                        />
                        <div className="absolute top-2 left-2 bg-black/40 backdrop-blur px-2 py-1 rounded-lg text-white">
                            {look.type === 'hair' ? <Scissors size={12} /> : <Shirt size={12} />}
                        </div>
                        <button 
                            onClick={(e) => handleDelete(e, look.id)}
                            className="absolute top-2 right-2 bg-white/80 p-1.5 rounded-full text-red-500 opacity-0 group-hover:opacity-100 transition-opacity shadow-sm"
                        >
                            <Trash2 size={14} />
                        </button>
                    </div>
                    <div className="p-3 flex-1 flex flex-col justify-between">
                        <div>
                             <h4 className="font-bold text-sm text-neutral dark:text-white line-clamp-1">{look.prompt}</h4>
                             <p className="text-[10px] text-gray-400 dark:text-gray-500 mt-1 flex items-center gap-1">
                                <Clock size={10} />
                                {new Date(look.timestamp).toLocaleDateString()}
                            </p>
                        </div>
                        <div className="flex gap-2 mt-3">
                            <button 
                                onClick={(e) => handleDownload(e, look)}
                                className="flex-1 flex items-center justify-center gap-1 bg-gray-50 dark:bg-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 text-neutral dark:text-gray-200 text-[10px] font-bold py-2 rounded-lg transition-colors border border-gray-200 dark:border-gray-600"
                            >
                                <Download size={12} /> Save
                            </button>
                            <button 
                                onClick={(e) => handleShare(e, look)}
                                className="flex-none w-8 flex items-center justify-center bg-gray-50 dark:bg-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 text-neutral dark:text-gray-200 rounded-lg border border-gray-200 dark:border-gray-600"
                            >
                                <Share2 size={12} />
                            </button>
                        </div>
                    </div>
                </div>
            ))}
        </div>
    </div>
  );
};
